// Regenerates the deterministic half of examples/sample-report.json (the
// `plies`, `definingMoves`, and `score` fields) from examples/sample-game.pgn
// — everything computed here is real output from the shipped
// src/lib/councilScore.js, run against the exact same swing values used
// when this example was approved as the target structure.
//
// What this script CANNOT regenerate: the prose (`report.historian`,
// `report.strategistSam`, `report.endgameEd`, `report.coachPriya`,
// `report.definingMoveNotes[].caption`) — that's server/council.js's job,
// which needs a live ANTHROPIC_API_KEY. The prose in sample-report.json
// was hand-written to the exact target voice/schema as a worked example,
// not generated by a live call, and should be treated as a fixture to
// compare future real output against — not overwritten by re-running
// this script.
//
// Why the eval swings below are hand-assigned rather than engine-computed:
// this game was analyzed by hand (verified material counting) rather than
// through a live Stockfish run when this example was built — see the
// module README's "Example report" section. Run with real analyzeGame()
// output instead once a live engine run against this same PGN is
// available, and diff the two — they should tell the same story even if
// exact centipawn numbers differ.
//
// Usage: node examples/generate-sample.mjs

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Chess } from "chess.js";
import { computeCouncilScore } from "../src/lib/councilScore.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pgn = readFileSync(join(__dirname, "sample-game.pgn"), "utf8");

// swing = centipawn eval change from the MOVER's own perspective, same
// convention as src/lib/gameAnalysis.js. Verified against a hand material
// count of this specific game (see the design conversation this example
// came out of) — every other ply defaults to 0 (treated as "normal").
const SWINGS = {
  16: -90, // 8...Rg8 - wasted tempo, first sign Black won't castle
  18: -90, // 9...Rh8 - wasted tempo again
  39: -620, // 20.Rxf6 - queen left hanging on h5, the big sacrifice
  40: 600, // 20...Qxh5 - Black grabs the hanging queen
  41: 320, // 21.Rxd6 - the point of the combo, recoups a bishop
  45: -520, // 23.g4 - misses the hanging rook on d6
  46: 520, // 23...Qxd6 - Black wins the rook back
  63: 300, // 32.Nxe4 - White wins the bishop back cleanly
  72: -510, // 36...Rc3+ - checks into a square the knight covers, loses the rook
  73: 510, // 37.Nxc3 - White capitalizes
};

function classify(swing) {
  if (swing <= -300) return "blunder";
  if (swing <= -150) return "mistake";
  if (swing <= -75) return "inaccuracy";
  if (swing >= 200) return "excellent";
  return "normal";
}

function pickDefiningMoves(plies, maxCount = 6) {
  const flagged = new Map();
  const add = (p) => {
    if (p) flagged.set(p.ply, p);
  };
  add(plies.find((p) => p.isCheckmate));
  add(plies[plies.length - 1]);
  add(plies.find((p) => p.classification === "blunder"));
  const byMag = [...plies].sort((a, b) => Math.abs(b.swing) - Math.abs(a.swing));
  for (const p of byMag) {
    if (flagged.size >= maxCount) break;
    if (p.classification === "normal") continue;
    add(p);
  }
  return [...flagged.values()].sort((a, b) => a.ply - b.ply);
}

const walker = new Chess();
walker.loadPgn(pgn);
const moveList = walker.history({ verbose: true });
const replay = new Chess();

let evalWhite = 0;
const plies = moveList.map((move, i) => {
  const applied = replay.move({ from: move.from, to: move.to, promotion: move.promotion });
  const ply = i + 1;
  const swingForMover = SWINGS[ply] ?? 0;
  const moverSign = applied.color === "w" ? 1 : -1;
  evalWhite += moverSign * swingForMover;
  return {
    ply,
    moveNumber: Math.floor(i / 2) + 1,
    color: applied.color,
    san: applied.san,
    isCapture: Boolean(applied.captured),
    isCastle: applied.san === "O-O" || applied.san === "O-O-O",
    isCheckmate: applied.san.includes("#"),
    isCheck: applied.san.includes("+") && !applied.san.includes("#"),
    evalCp: evalWhite,
    mate: null,
    swing: swingForMover,
    classification: classify(swingForMover),
  };
});

const definingMoves = pickDefiningMoves(plies);
const result = "1-0";

console.log(
  JSON.stringify(
    {
      definingMoves,
      scoreWhite: computeCouncilScore({ plies, perspective: "w", result }),
      scoreBlack: computeCouncilScore({ plies, perspective: "b", result }),
    },
    null,
    2
  )
);
